# Generated by Django 6.1.1 on 2026-09-12 21:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRateSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(default='exchangerate-api', max_length=64)),
                ('base_code', models.CharField(max_length=3)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('succeeded', models.BooleanField(default=True)),
                ('message', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, validators=[django.core.validators.RegexValidator(message="Use a 3-letter uppercase ISO 4217 code, for example 'EUR'.", regex='^[A-Z]{3}$')])),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(blank=True, max_length=8)),
                ('exchange_rate', models.DecimalField(decimal_places=12, help_text='Units of this currency per 1 unit of the base currency.', max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('1E-12'))])),
                ('principal', models.BooleanField(default=False, help_text='The app-wide reporting currency. Exactly one currency has this set.')),
                ('is_active', models.BooleanField(default=True)),
                ('rate_updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'currencies',
                'ordering': ['code'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('principal', True)), fields=('principal',), name='unique_principal_currency'), models.CheckConstraint(condition=models.Q(('exchange_rate__gt', 0)), name='currency_exchange_rate_positive')],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=12, max_digits=24)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_history', to='currencies.currency')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='currencies.exchangeratesnapshot')),
            ],
            options={
                'ordering': ['-snapshot__fetched_at'],
                'constraints': [models.UniqueConstraint(fields=('snapshot', 'currency'), name='unique_rate_per_snapshot')],
            },
        ),
    ]
