# Generated by Django 6.1.1 on 2026-09-12 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(help_text="ISO 4217 code, for example 'EUR'. Stored uppercase.", max_length=3, unique=True),
        ),
    ]
