# Generated by Django 6.1.1 on 2026-09-12 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_mutating_operations', models.BooleanField(default=True, help_text='When off, only read-only operations (checks, statistics) may be run from the console.')),
                ('allow_destructive_operations', models.BooleanField(default=False, help_text='Required for operations such as running migrations from the console.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'operations settings',
                'verbose_name_plural': 'operations settings',
            },
        ),
        migrations.CreateModel(
            name='OperationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(db_index=True, max_length=64)),
                ('arguments', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='running', max_length=16)),
                ('output', models.TextField(blank=True, default='')),
                ('error', models.TextField(blank=True, default='')),
                ('result', models.JSONField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'operation run',
                'verbose_name_plural': 'operation runs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['operation', '-started_at'], name='ops_operati_operati_af6207_idx')],
            },
        ),
    ]
