# Generated by Django 6.1.1 on 2026-09-19 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_import_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-transaction_date', '-created_date', '-id']},
        ),
    ]
