# Generated by Django 6.1.1 on 2026-09-12 21:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currencies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('checking', 'Checking'), ('savings', 'Savings'), ('credit', 'Credit card'), ('cash', 'Cash'), ('investment', 'Investment'), ('loan', 'Loan'), ('other', 'Other')], default='checking', max_length=16)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('-999999999999999999.99'))])),
                ('institution', models.CharField(blank=True, default='', max_length=200)),
                ('official_number', models.CharField(blank=True, default='', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive accounts are hidden but keep their history.')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='currencies.currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='accounts_ac_user_id_0bca0f_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'name'), name='unique_account_name_per_user')],
            },
        ),
    ]
