# Generated by Django 6.1.1 on 2026-09-12 21:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('currencies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('accounts', models.ManyToManyField(blank=True, related_name='budgets', to='accounts.account')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='currencies.currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date', 'name'],
                'indexes': [models.Index(fields=['user', 'start_date', 'end_date'], name='budgets_bud_user_id_ea9bf3_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('max_amount__gte', models.F('min_amount'))), name='budget_max_gte_min'), models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='budget_end_after_start')],
            },
        ),
    ]
