# Generated by Django 6.1.1 on 2026-09-12 21:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('currencies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=32)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('kind', models.CharField(choices=[('stock', 'Stock'), ('etf', 'ETF'), ('fund', 'Mutual fund'), ('bond', 'Bond'), ('crypto', 'Crypto'), ('real_estate', 'Real estate'), ('other', 'Other')], default='stock', max_length=16)),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=28, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('cost_basis', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount paid for the position, fees included.', max_digits=20)),
                ('opened_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, help_text='Optional: the account this position is held in.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holdings', to='accounts.account')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holdings', to='currencies.currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='Valuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valued_on', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to='investments.holding')),
            ],
            options={
                'ordering': ['-valued_on'],
            },
        ),
        migrations.AddConstraint(
            model_name='holding',
            constraint=models.UniqueConstraint(fields=('user', 'symbol', 'account'), name='unique_holding_per_account'),
        ),
        migrations.AddConstraint(
            model_name='valuation',
            constraint=models.UniqueConstraint(fields=('holding', 'valued_on'), name='unique_valuation_per_day'),
        ),
    ]
